### ISSUE TITLE
Roadmap/issues request.

### ISSUE THREAD

**Issue by snaptools2023** [little-fort/booster-bot#33]
Do you have a list of issues that you need a hand with?  Or a roadmap of things you would like to work on next?

**Comment by little-fort** [comment]
Nothing in particular, everything has been quite stable for the past couple months. I'll patch minor issues as I notice them but there hasn't been anything significant in a while.

I don't have any new features planned right now as the app is serving its purpose, though I'm certainly open to feedback. Otherwise it'll probably be pretty quiet unless SD makes a major update to the game that either breaks the app or adds new things that would be useful to integrate

**Comment by Mrstunk** [comment]
Auto-retreat at start of turn 4 option would be great for some dailies and more efficient exp farm.

**Comment by Gazebsssr** [comment]
> Auto-retreat at start of turn 4 option would be great for some dailies and more efficient exp farm.

I agree with you, there are now a lot of people in Conquest mode three round retreat, some people find that Conquest mode can now break the daily experience cap, some people can brush more than 20 times a day.

**Comment by little-fort** [comment]
Yeah I can add turn 4 auto-retreat, should be pretty simple. I'm currently trying to progress a different project but I'll try to get this updated soon

**Comment by little-fort** [comment]
@Mrstunk @Gazebsssr New release is up with optional auto-retreat:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.0

Let me know how it works for you. Thanks to @snaptools2023 for helping out with this one 🙂

**Comment by Mrstunk** [comment]
Works perfectly! Thank you for the implementation.  Got plenty of seasonpass caches and way too many gold ticket thanks to my Agatha/move deck.

**Comment by snaptools2023** [comment]
This request is stale.  Closing.  If I can help with anything, please ping me.
