### ISSUE TITLE
Anyway to make Conquest identifiable with or without LTMs?

### ISSUE THREAD

**Issue by yhussain1** [little-fort/booster-bot#84]
Hey buddy hope your well. Thanks for the work youve done with the bot its been a miracle with avoiding the grindfest. Its a shame SD decided to cap Season Cache levels. With Deadpools Diner out the bot cant get into Conquest anymore which is a problem as SD inconveniently put DD at the end of the month when ive hoarded all my tickets for Conquest. Any chance you could make it so it can identify conquest regardless of if theres an LTM or not?

**Comment by little-fort** [comment]
If you're using version 1.4.11 or higher, you can start the program with the `-e` or `--event` parameter and it will adjust the menu navigation to account for the event button. If you're on the latest version (1.6.0), you can alternatively set the `eventModeActive` option to `true` in the `appsettings.json` file to do this as well

I prefer this approach over baked-in detection because it's possible that the exact positioning of the word "Conquest" in that menu could change, and then it could still get broken every time. But I figure the button itself is likely to stay roughly the same size, so it's easier to just let users adjust the click point as needed

**Comment by yhussain1** [comment]
thanks for confirming that. i will make sure to do it that way from now on.
